### ISSUE TITLE
Plugin Twig Template + Possible Font Awesome conflict

### ISSUE THREAD

**Issue by paulhibbitts** [hexplor/grav-plugin-latest-tweets#1]
Hi @hexplor , I know I am early here but I am really excited to see your new Twitter feed Plugin🙂

A question and possible issue:

1. Can I use an include statement in Twig to include the default Twig Template that is in the Plugin folder or do I need to copy that Template to my own Partials folder?

2. When I enabled your Plugin I noticed some Font Awesome icons were not displaying right in my Course Hub theme (Bootstrap based), for example:

![2018-05-24_13-45-44](https://user-images.githubusercontent.com/1812771/40512989-520293a2-5f59-11e8-97b6-36507bdb3156.png)

Any thoughts on why this might be happening? Disabling the plugin results in the Font Awesome icons displaying correctly.

Thanks again for the really promising looking Plugin!
Paul

**Comment by hexplor** [comment]
Hey,
Thank you :)
Yes, you should be able to include plugin file like that

```{% include 'partials/latest-tweets.html.twig' %}```

Regarding font awesome there might be some issues in fact, i just included external fa css file for that. Might want to re-check. Anyways .. your screenshot is not opening for me :)

**Comment by paulhibbitts** [comment]
Thanks very much @hexplor , that example Twig is very helpful.
 
Re: Font Awesome issue, indeed this is in a theme that already adds Font Awesome as an asset. Here is another screenshot, I hope this one displays ok: https://cl.ly/2y2J0m0K3G0z It shows an icon displayed as a box with hex code inside of it.

Happy to test any changes and report back to you, and I can send you a zip file of my user folder if that helps.

**Comment by hexplor** [comment]
Hey man,
Thank you so much. I will definitely came up with better solution regarding Font Awesome in next few days. Stay tuned :)

**Comment by hexplor** [comment]
Hi @paulhibbitts can you send me your user folder ?

**Comment by hexplor** [comment]
Added ability to disable font awesome in latest release.
