### ISSUE TITLE
Avatar image url over http

### ISSUE THREAD

**Issue by CSixtyFour** [hexplor/grav-plugin-latest-tweets#2]
Hi
My whole site is https but the image url from `{{ item.user.profile_image_url }}` is coming through as http and causing a mixed content warning. I've taken a quick look but I'm not seeing where this url is generated.

**Comment by hexplor** [comment]
Solution is actually very simple, I will commit update later but right now you can just rework:

```{{ item.user.profile_image_url }}```
to
```{{ item.user.profile_image_url|replace({'http://':'https://'}) }}```

**Comment by CSixtyFour** [comment]
oh man so simple!

Thanks for a really useful plugin.

**Comment by hexplor** [comment]
Fixed in repo :) Enjoy and thanks !!
